import Navbar from "@/components/Navbar"
import { Inter } from 'next/font/google'
import './globals.css'
import MultiLayerParallax from "@/components/MultiLayerParallax"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-10xl h-svh mx-auto">
          <div className="flex bg-white">
            <Navbar />
            <div className="w-4/6 bg-black">
              <MultiLayerParallax />
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
